service: freshworks-data

provider:
  name: aws
  runtime: nodejs14.x

functions:
  getFreshcaller:
    handler: build/index.getFreshcaller
    timeout: 900
    url: true
  getFreshchat:
    handler: build/index.getFreshchat
    timeout: 900
    url: true
